// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBngB4CcMyEIQu2kxYuLg8BzpA1lDb0bkU',
    appId: '1:208090738802:web:b6e97fd8f3af103e6c52eb',
    messagingSenderId: '208090738802',
    projectId: 'msi-ses2223-g06',
    authDomain: 'msi-ses2223-g06.firebaseapp.com',
    storageBucket: 'msi-ses2223-g06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGMsY6ZRGXpuuY-26ZtoRqRHT7XUUk0bc',
    appId: '1:208090738802:android:8ec7c57bc60905d56c52eb',
    messagingSenderId: '208090738802',
    projectId: 'msi-ses2223-g06',
    storageBucket: 'msi-ses2223-g06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW1u3vE2PwGY42ZxcCAebN7qUERrbhqCE',
    appId: '1:208090738802:ios:93a1b0c24a17494e6c52eb',
    messagingSenderId: '208090738802',
    projectId: 'msi-ses2223-g06',
    storageBucket: 'msi-ses2223-g06.appspot.com',
    iosClientId: '208090738802-uakjroadnktdk1i4nr6hbge85bb8io7n.apps.googleusercontent.com',
    iosBundleId: 'pt.up.fc.msi.ses.g06.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW1u3vE2PwGY42ZxcCAebN7qUERrbhqCE',
    appId: '1:208090738802:ios:3905958138d738eb6c52eb',
    messagingSenderId: '208090738802',
    projectId: 'msi-ses2223-g06',
    storageBucket: 'msi-ses2223-g06.appspot.com',
    iosClientId: '208090738802-51kjnnle6c9vq92oots8tftabt9g5g7f.apps.googleusercontent.com',
    iosBundleId: 'pt.up.fc.msi.ses.g06.app.RunnerTests',
  );
}
